### ISSUE TITLE
Script to check airdrop JSON vs allocation

### ISSUE THREAD

**Issue by embiem** [Developer-DAO/code-claim-site#4]
A script that should confirm that the created airdrop JSON sums up to be equal to the token allocations. This is meant as a final sanity-check.

The [token proposal](https://snapshot.org/#/devdao.eth/proposal/0x6c141b9efbfad6b370581eebf505408ba7f8619264b7e8ca03118fdf89975c97) allocates 25% to NFT Holders & Early Voters/POAP Holders and another 10% to Early Contributors.

All amounts in the airdrop file at `packages\hardhat\data\airdrop.json` should therefore sum-up to 3_500_000.

**Comment by kseikyo** [comment]
Can someone assign this for me? Will send a PR soon.

**Comment by janndriessen** [comment]
Not sure what @embiem had in mind. Make sure to post questions on the discord channel as well. This way it's easier to follow for everyone.

**Comment by kseikyo** [comment]
Something like this should do the trick (in js), but I'm not sure where to add it to be run.

```javascript
const isAirdropSumCorrect = () => {
  const EXPECTED_SUM = 3_500_000;
  
  const AIRDROP_URL = '<url_to_file>';
  
  const airdropData = JSON.parse(fs.readFileSync(AIRDROP_URL).toString());
  
  const tokenList = Object.values(airdropData);
  
  const airdropSum = tokenList.reduce((acc, value) => {
    return acc + value;
  }, 0);
  
  return airdropSum === EXPECTED_SUM;
}
```

**Comment by embiem** [comment]
Hey! Thanks for contributing!

The script should go in packages/hardhat/scripts.

Best would be to take the inputs like path to airdrop from the args.

Thanks a lot!

**Comment by kseikyo** [comment]
Hey, just finished writing this, can you add me to the org so I can push a new branch and make a PR.

It's okay if not, I can just fork the project and make a PR like that anyway.

Here's what I got
```typescript
// packages/hardhat/scripts/getAirdropSum.ts
import { readFileSync } from 'fs';

const isAirdropSumCorrect = (AIRDROP_URL: string) => {
  const EXPECTED_SUM = 3_500_000;

  const airdropData = JSON.parse(readFileSync(AIRDROP_URL).toString());

  const tokenList: Array<number> = Object.values(airdropData);

  const airdropSum = tokenList.reduce((acc, value) => {
    return acc + value;
  }, 0);

  return airdropSum === EXPECTED_SUM;
};

```

**Comment by embiem** [comment]
@kseikyo just added you as collaborator on the project. You should be able to create a branch now.

For the org you'll have to ask in Discord in #github-org-invitations.
