### ISSUE TITLE
UI: Claim Card Component

### ISSUE THREAD

**Issue by embiem** [Developer-DAO/code-claim-site#5]
Figma: https://www.figma.com/file/TiqfRJnNxOQOSjA2TMkagD/%24CODE-Airdrop-Site-Designs

## States
The UI component for the claim card has 4 states:

1. before the wallet is connected:
![claim-card_0_pre-connect](https://user-images.githubusercontent.com/3866457/150329706-edab128c-bc21-408b-a5a4-aa30dc4bea6e.png)

2. after the wallet is connected and the user hasn't claimed yet:
![claim-card_1_connected-pre-claim](https://user-images.githubusercontent.com/3866457/150329718-4706eb20-f4d1-4312-a947-ab1ff674a512.png)

3. while the user is claiming (signing transaction, waiting for tx to finish etc.): _no specific design yet_

4. after the wallet is connected and once the user has claimed: _no specific design yet_

## Mobile

The card should shrink in width. No specific design change:

![claim-card_mobile](https://user-images.githubusercontent.com/3866457/150329726-9552522e-b456-4fa4-a2eb-482d9eebc72a.png)

## Props

Suggested props:

```
{
  hasClaimed: boolean;
  isClaiming: boolean;
  allocations: {
    member: number;
    voterOrPoap: number;
    earlyContributor: number;
  }
}
```

**Comment by janndriessen** [comment]
Looking into this. Currently, can't assign myself - as I still seem to miss some permissions.

**Comment by embiem** [comment]
@janndriessen you should now have write permissions to the repo.
